export const RESPONSES = {
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NOCONTENT: 204,
    BADREQUEST: 400,
    UN_AUTHORIZED: 401,
    INVALID_REQ: 422,
    FORBIDDEN: 403,
    NOTFOUND: 404,
    CONFLICT: 409,
    TIMEOUT: 408,
    TOOMANYREQ: 429,
    INTERNALSERVER: 500,
    BADGATEWAYS: 502,
    SERVICEUNAVILABLE: 503,
    GATEWAYTIMEOUT: 504,
};
export const RES_MSG = {
    DATA_SUCCESS: 'Data fetched successfully',
    DATA_INSERT: 'Data inserted successfully',
    NO_DATA: 'No data found',
    BADREQUEST: 'Not a Valid Request',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    SUCCESS: 'Success',
    INVALID_USER: 'Invalid User',
    SMTHNG_WRNG: 'Something went wrong',
    LOGIN_SUCCESS: 'Logged In Successfully',
    WRONG_PASSWORD: 'Wrong Password',
    VERIFY_2FA: 'Please verify 2FA',
    UNAUTHORISED: 'You are not Authorised',
    DOB_RQRD: 'Date of Birth is required.',
    AGE_RESTRICTION: 'You must be at least 18 years old.',
    SIGNUP_SUCCESS: 'Sign Up successfull',
    SIGNUP_CONFLICT: 'Details are Already Exist',
    INVALID_LOGIN: 'Invalid password or email',
    TOO_MANY_REQ: 'Too many Requests from this IP, please try again after an hour',
};
